Repository feldroy/air, pull requests merged in 2025-08, with the labels that each got.

#228 Document how to use forms Starlette style
  docs/concepts/forms.md
Labels: docs

#234 Remove deprecated Jinja2Renderer
  src/air/__init__.py
  src/air/templates.py
  tests/test_templates.py
Labels: python

#235 Begin phasing out content in docs
  docs/about/alternatives.md
  docs/about/history.md
  docs/about/index.md
  docs/concepts/air_tags.md
  docs/concepts/escaping_html.md
  docs/concepts/forms.md
  docs/concepts/index.md
  docs/concepts/jinja.md
  docs/concepts/layouts.md
  docs/index.md
  mkdocs.yml
Labels: docs

#236 Better types for width and height tag attrs
  src/air/tags.py
Labels: python, feature, Air Tags

#238 Add issue templates for bugs, features, discussions, etc
  .github/issues/config.yml
Labels: upgrade

#249 Refactor EventStreamResponse to SSEResponse
  src/air/__init__.py
  src/air/responses.py
  src/air/tags.py
  tests/test_responses.py
  tests/test_tags.py
Labels: python, feature

#257 BUG: SSEResponse now Handles str and Tag types, with linebreaks handled cleanly
  src/air/responses.py
  src/air/tags.py
  tests/test_responses.py
  tests/test_tags.py
Labels: bug, python, feature, Air Tags

#262 Feat pyproject.toml - Part 2
  CONTRIBUTING.md
  justfile
  pyproject.toml
  uv.lock
Labels: dependencies, refactor

#265 Use HTML page for 500 errors
  src/air/applications.py
  tests/test_applications.py
Labels: python, upgrade

#266 Convert default exception handlers to use mvpcss for layout
  src/air/applications.py
  src/air/layouts.py
  tests/test_applications.py
Labels: upgrade

#275 Switch from pytest-rich to pytest-modern
  .env
  pyproject.toml
Labels: bug, dependencies, python

#279 Improve CI workflows, annotations in the GitHub using GitHub Actions and CI for ubuntu-latest, windows-latest, macos-latest
  .github/workflows/python-package.yml
  .github/workflows/release-to-pypi.yml
  README.md
  pyproject.toml
  uv.lock
Labels: dependencies, upgrade

#293 Convert underscores to dashes in app.page method
  src/air/applications.py
  tests/test_applications.py
Labels: python, feature

#296 Docstring improvements
  src/air/responses.py
  src/air/tags/models/stock.py
Labels: docs

#297 Document docstring management in CONTRIBUTING.md
  CONTRIBUTING.md
  pyproject.toml
  src/air/applications.py
Labels: docs

#298 Add module level docstrings
  src/air/applications.py
  src/air/background.py
  src/air/forms.py
  src/air/layouts.py
  src/air/requests.py
  src/air/responses.py
  src/air/tags/models/base.py
  src/air/tags/models/special.py
  src/air/tags/models/stock.py
  src/air/tags/models/svg.py
  src/air/tags/utils.py
  src/air/templates.py
Labels: docs

#317 FEAT: AirForm.validate method returns boolean instead of None
  src/air/forms.py
  tests/test_forms.py
  uv.lock
Labels: python, feature

#327 Fixes #326
  src/air/forms.py
  src/air/tags/models/base.py
  tests/test_tags.py
Labels: bug, Air Tags

#330 Rearrange MVPCSS docs
  src/air/layouts.py
Labels: docs

#334 Add SessionMiddleware class
  pyproject.toml
  src/air/__init__.py
  src/air/middleware.py
  tests/test_middleware.py
  uv.lock
Labels: deps, python, feature

#324 BUG: Add missing autofocus option to AirField
  src/air/forms.py
  tests/test_forms.py
Labels: bug, python, Air Tags

#346 Run ruff on code after enabling more rules
  .editorconfig
  justfile
  pyproject.toml
  src/air/applications.py
  src/air/background.py
  src/air/forms.py
  src/air/middleware.py
  src/air/requests.py
  src/air/responses.py
  src/air/tags/models/special.py
  src/air/tags/models/svg.py
  src/air/tags/utils.py
  src/air/templates.py
  tests/__init__.py
  tests/benchmarks/README.md
  tests/benchmarks/__init__.py
  tests/benchmarks/test_html_rendering_benchmark.py
  tests/benchmarks/test_jinja_rendering_benchmark.py
  tests/benchmarks/test_memory_tag_cleanup.py
  tests/benchmarks/test_tag_creation_benchmark.py
  tests/test_forms.py
  tests/test_layouts.py
  tests/test_middleware.py
  tests/test_requests.py
  tests/test_responses.py
  tests/test_tags.py
  uv.lock
Labels: refactor, Status: Mergable ✅, Status: Review Needed 💬

#359 Refactor locals cleanup utility and streamline attribute handling
  src/air/tags/config.py
  src/air/tags/models/stock.py
  src/air/tags/models/svg.py
  src/air/tags/utils.py
  tests/test_forms.py
  tests/test_tags_utils.py
Labels: Status: Do Not Merge! ❌, Status: Review Needed 💬

#361 Implement hx boost in layout functions
  examples/mvpcss_hxboost.py
  src/air/applications.py
  src/air/dependencies.py
  src/air/layouts.py
  tests/test_applications.py
  tests/test_layouts.py
  tests/test_requests.py
Labels: python, feature

#364 Remove mkdocs
  docs/api/applications.md
  docs/api/background.md
  docs/api/forms.md
  docs/api/index.md
  docs/api/layouts.md
  docs/api/requests.md
  docs/api/responses.md
  docs/api/svg/a-d.md
  docs/api/svg/e-m.md
  docs/api/svg/index.md
  docs/api/svg/n-s.md
  docs/api/svg/t-z.md
  docs/api/tags/a-d.md
  docs/api/tags/e-m.md
  docs/api/tags/index.md
  docs/api/tags/n-s.md
  docs/api/tags/t-z.md
  docs/api/templates.md
  docs/img/logo-blue-369x369.png
  docs/index.md
  mkdocs.yml
  pyproject.toml
  uv.lock
Labels: deps, docs

#365 Remove docs GH workflow
  .github/workflows/publish-docs.yml
Labels: github_actions, actions

#378 Add includes argument to AirForm rendering
  src/air/forms.py
  tests/test_forms.py
Labels: python, feature
