Repository feldroy/air, pull requests merged in 2025-09, with the labels that each got.

#426 Fix doc index links
  docs/about/index.md
  docs/cookbook/index.md
  docs/learn/index.md
Labels: bug, docs

#427 Fix errant doc links
  docs/tools.md
  docs/why.md
Labels: bug, docs

#377 Improve tag rendering
  CONTRIBUTING.md
  examples/html_sample.py
  examples/tags_render.py
  pyproject.toml
  src/air/__init__.py
  src/air/applications.py
  src/air/error_responses.py
  src/air/forms.py
  src/air/layouts.py
  src/air/responses.py
  src/air/routing.py
  src/air/tags/__init__.py
  src/air/tags/models/__init__.py
  src/air/tags/models/base.py
  src/air/tags/models/special.py
  src/air/tags/models/stock.py
  src/air/tags/models/svg.py
  src/air/tags/types.py
  src/air/tags/utils.py
  src/air/utils.py
  tests/test_applications.py
  tests/test_base_tag.py
  tests/test_layouts.py
  tests/test_requests.py
  tests/test_tags.py
  tests/test_templating.py
  uv.lock
Labels: Status: Mergable ✅, Status: Review Needed 💬

#431 Improve Justfile
  .editorconfig
  justfile
  pyproject.toml
Labels: Status: Mergable ✅, Status: Review Needed 💬

#439 Updated the example usage command to `just run-py-module examples.tags_render`.
  examples/tags_render.py
Labels: Status: Mergable ✅, Status: Review Needed 💬

#442 SQL doc cleanup and fix why page
  docs/api/ext/index.md
  docs/why.md
  src/air/ext/sql.py
Labels: bug, docs

#443 Add GitHub OAuth router Factory
  .gitignore
  docs/api/ext/auth.md
  docs/api/ext/index.md
  examples/github_oauth_demo.py
  mkdocs.yml
  pyproject.toml
  src/air/ext/__init__.py
  src/air/ext/auth.py
  tests/ext/test_auth.py
  uv.lock
Labels: deps, python, feature, upgrade, Status: Do Not Merge! ❌

#451 Added a new "all" group for combined optional dependencies in `pyproject.toml`
  CONTRIBUTING.md
  README.md
  justfile
  pyproject.toml
  uv.lock
Labels: Status: Mergable ✅, Status: Review Needed 💬

#452 Add missing doc pages
  docs/api/dependencies.md
  docs/api/exception_handlers.md
  docs/api/index.md
  docs/api/requests.md
  docs/api/routing.md
  docs/api/utils.md
  mkdocs.yml
  src/air/applications.py
  src/air/exception_handlers.py
  tests/test_applications.py
Labels: docs

#459 Small refactor extracted from a big PR
  justfile
  src/air/__init__.py
  src/air/tags/__init__.py
  src/air/tags/models/__init__.py
  src/air/templating.py
  tests/test_tags.py
Labels: Status: Mergable ✅, Status: Review Needed 💬

#441 Add type annotations to the entire codebase using pyrefly and ruff(What they could do, still not 100%)
  examples/instrument.py
  examples/mvpcss_layout.py
  justfile
  pyproject.toml
  src/air/ext/__init__.py
  src/air/ext/sql.py
  src/air/forms.py
  src/air/layouts.py
  src/air/responses.py
  src/air/tags/models/base.py
  src/air/tags/models/special.py
  src/air/tags/models/stock.py
  src/air/tags/models/svg.py
  src/air/tags/types.py
  src/air/templating.py
  tests/benchmarks/test_html_rendering_benchmark.py
  tests/benchmarks/test_jinja_rendering_benchmark.py
  tests/benchmarks/test_memory_tag_cleanup.py
  tests/benchmarks/test_tag_creation_benchmark.py
  tests/components.py
  tests/ext/test_auth.py
  tests/ext/test_sql.py
  tests/test_applications.py
  tests/test_background.py
  tests/test_exceptions.py
  tests/test_forms.py
  tests/test_layouts.py
  tests/test_middleware.py
  tests/test_requests.py
  tests/test_responses.py
  tests/test_routing.py
  tests/test_stock_tags_coverage.py
  tests/test_svg.py
  tests/test_tags.py
  tests/test_tags_utils.py
  tests/test_templating.py
  uv.lock
Labels: Status: Mergable ✅, Status: In Review 👀

#469 chore: update Codecov config and refine coverage exclusions
  .github/codecov.yml
  pyproject.toml
Labels: Status: Mergable ✅, Status: Review Needed 💬

#479 Make contributing.md more concise
  CONTRIBUTING.md
Labels: docs

#483 Merge cookbook into learn section
  docs/cookbook/jinja.md
  docs/index.md
  docs/learn/cookbook/authentication.md
  docs/learn/cookbook/bigger-applications.md
  docs/learn/cookbook/charts.md
  docs/learn/cookbook/checklist.md
  docs/learn/cookbook/forms.md
  docs/learn/cookbook/index.md
  docs/learn/cookbook/minimal.md
  docs/learn/cookbook/page-decorator.md
  docs/learn/cookbook/static.md
  docs/learn/index.md
  docs/learn/jinja.md
  mkdocs.yml
Labels: docs

#493 Various minor fixes to documentation
  docs/api/ext/sql.md
  docs/learn/air_tags.md
  docs/learn/cookbook/index.md
  docs/learn/index.md
  docs/learn/quickstart.md
  docs/learn/sql.md
  docs/learn/tutorial.md
Labels: docs

#501 Bring forward old version release instructions
  MAINTAINERS.md
Labels: docs

#508 Move alternatives to use admonitions
  docs/about/alternatives.md
  mkdocs.yml
Labels: docs

#513 Add airblog example
  examples/airblog.py
  examples/airblog/hello-world.md
  examples/airblog/markdown-features.md
Labels: python, docs
